name: Proxy Build

on:
  push:
    branches:
      - main
    paths:
      - 'python_proxy/*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@v0.1.2
        with:
          path: python_proxy
          spec: WSProxy.spec
          
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: python_proxy/dist/cannyadachiProxy.exe
